apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: test
  name: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      run: test
  template:
    metadata:
      labels:
        run: test
    spec:
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: blue
      volumes:
      - name: blue
        configMap:
          name: blue
